# Generated by Django 4.2.11 on 2026-05-18 07:15

from django.db import migrations, models


try:
    import cloudinary.models
except ImportError:
    cloudinary = None


def optional_cloudinary_field(resource_type='image', **kwargs):
    if cloudinary:
        return cloudinary.models.CloudinaryField(resource_type=resource_type, **kwargs)
    return models.FileField(**kwargs)


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0025_cloudinary_media_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='trainer_image',
            field=optional_cloudinary_field(blank=True, max_length=255, null=True, resource_type='image'),
        ),
        migrations.AlterField(
            model_name='workoutitem',
            name='video',
            field=optional_cloudinary_field(blank=True, max_length=255, null=True, resource_type='video'),
        ),
    ]
